In [5]:
!pip install pymysql
import pymysql

Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 2.1 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1

In [9]:
conexao = pymysql.connect(
    host= '52.206.8.150',
    user= 'aluno',
    password= 'aluno',
    port=3306
)

cursor = conexao.cursor()

In [10]:
cursor.execute("show databases")

for i in cursor:
  print(i)

('faculdade',)
('information_schema',)
('performance_schema',)

In [11]:
cursor.execute('use faculdade')

0

In [24]:
cursor.execute('create table usuarios(id_usuario int auto_increment primary key, nome_usuario varchar(100), cpf varchar (50), telefone varchar(100))')

0

In [25]:
sql = "INSERT INTO usuarios (nome_usuario, cpf, telefone) VALUES (%s, %s, %s)"
val = [
    ("John", "52292345678", "11998765432"),
  ("Deivid", "52348902134", "12965431212")
]

cursor.executemany(sql, val)

conexao.commit()

print(cursor.rowcount, "record inserted.")

2 record inserted.

In [14]:
cursor.execute("SELECT * FROM usuarios")

myresult = cursor.fetchall()

for x in myresult:
  print(x)

(1, 'John', '52292345678', '11998765432')
(2, 'Deivid', '52348902134', '12965431212')

In [18]:
sql = "SELECT * FROM usuarios WHERE nome_usuario ='Deivid'"

cursor.execute(sql)

myresult = cursor.fetchall()

for x in myresult:
  print(x)

(2, 'Deivid', '52348902134', '12965431212')

In [20]:
sql = "SELECT * FROM usuarios ORDER BY nome_usuario"

cursor.execute(sql)

myresult = cursor.fetchall()

for x in myresult:
  print(x)

(2, 'Deivid', '52348902134', '12965431212')
(1, 'John', '52292345678', '11998765432')

In [22]:
sql = "DELETE FROM usuarios WHERE nome_usuario = 'John'"

cursor.execute(sql)

conexao.commit()

print(cursor.rowcount, "record(s) deleted")

1 record(s) deleted

In [23]:
sql = "DROP TABLE usuarios"

cursor.execute(sql)

0

In [26]:
sql = "UPDATE usuarios SET cpf = '98765432100' WHERE cpf = '52348902134'"

cursor.execute(sql)

conexao.commit()

print(cursor.rowcount, "record(s) affected")

1 record(s) affected

In [27]:
cursor.execute("SELECT * FROM usuarios LIMIT 1")

myresult = cursor.fetchall()

for x in myresult:
  print(x)

(1, 'John', '52292345678', '11998765432')

In [28]:
cursor.execute('create table cursos(id_curso int auto_increment primary key, nomecurso varchar(100), tipo varchar (50), preco varchar(100))')

0

In [29]:
sql = "INSERT INTO cursos (nomecurso, tipo, preco) VALUES (%s, %s, %s)"
val = [
    ("Mecânica", "Technology", "R$4.800,00"),
  ("T.I", "Technology", "R$5.000,00")
]

cursor.executemany(sql, val)

conexao.commit()

print(cursor.rowcount, "record inserted.")

2 record inserted.

In [31]:
sql = "SELECT \
  usuarios.nome_usuario AS user, \
  cursos.nomecurso AS favorite \
  FROM usuarios \
  INNER JOIN cursos ON usuarios.id_usuario = cursos.id_curso"

cursor.execute(sql)

myresult = cursor.fetchall()

for x in myresult:
  print(x)

('John', 'Mecânica')
('Deivid', 'T.I')